### ISSUE TITLE
Zoom out button not available in the google map  

### ISSUE THREAD

**Issue by dkusbit** [CMU-Socius/Socius#18]
<img width="944" alt="screen shot 2018-05-16 at 10 00 20 am" src="https://user-images.githubusercontent.com/38955010/40121705-2b59f502-58f0-11e8-9fe1-5504bd319b5c.png">

This appears to be the case in both mobile and desktop version of the app on the new requests page.

**Comment by spark33** [comment]
This is a tricky one, since it involves "hacking" the Google Map. It could either be a super quick fix or something that takes me several hours.
